#! /usr/bin/python

import os;
Import( "src_env" );
Import( "src_dir" );

tmp = [];
for i in os.listdir( src_dir ):
	if i.endswith( ".cpp" ):
		tmp.append( i );

src_env.StaticLibrary( "libg2", tmp );
